### ISSUE TITLE
alright

### ISSUE THREAD

**Issue by iop3** [darkdarcool/darkdarcool#2]
> (busy) 🎮 Just got hollow knight! Be back when beaten

good luck.

**Comment by darkdarcool** [comment]
LOl, I have the power of Google, and having beaten cuphead 100% on my side, AAAAAAHHHhHhHhHhHHHHhHHHHHHhHh

**Comment by darkdarcool** [comment]
(You get the meme)

**Comment by iop3** [comment]
lol ok

**Comment by darkdarcool** [comment]
EAT IT. JUST BEAT HOLLOW KNIGHT AND THE RADIANCE FIRST TRY!!!!

**Comment by iop3** [comment]
nice job

**Comment by darkdarcool** [comment]
:)
