### ISSUE TITLE
How did you get a great profile picture?

### ISSUE THREAD

**Issue by iop3** [darkdarcool/darkdarcool#3]
I have a very stupid question that requires 0 iq to ask because your profile is very epic.

(trash talk ⬆)

Anyways...how did u make it. tell me. i will give you nothing in return 🍰

**Comment by darkdarcool** [comment]
Friend gave it to me. I have no idea where he go it

**Comment by iop3** [comment]
ok, how did you get a good readme for your profile then? @darkdarcool

**Comment by darkdarcool** [comment]
carbon

**Comment by iop3** [comment]
ok
